name = "SymEngineExt"
uuid = "eb43aea2-30a6-470d-b25b-3f3789752db4"
authors = ["zhaoli-IHEP <zhaoli@ihep.ac.cn>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
