name = "AmpTools"
uuid = "052ca545-3a01-4253-8448-a7bfac913c46"
authors = ["zhaoli-IHEP <zhaoli@ihep.ac.cn>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
